equipData["Fighter"] = {
    subCategories: [
        { id: "ft-light", name: "Giáp Light đơn" }
    ],
    tierlists: {}
};

equipDetails["Fighter"] = {
    "rainbow_ft": {
        "la-9": {
            name: "Lavochkin La-9 (Carrier-based Prototype)",
            tier: "SS-",
            source: ["PR7 Research"],
            faction: "Northern Parliament",
            equippable: ["BBV", "CV", "CVL"],
            stats: ["AVI +65"],
            cannons: ["4x23_cannon_t0"],
            weapons: ["rocket_s_21"],
            weaponCount: [4],
            rld: ["11.70s"],
            linkTab: 0,
            desc: ["Không có khả năng đánh chặn"],
            code: "3/34/85600",
            box: "rainbow"
        },
    },
    "yellow_ft": {
        "f6f-hvar": {
            name: "Grumman F6F Hellcat (HVAR-Mounted)",
            tier: "S+",
            source: ["War Archives Drop", "A Note Through the Firmament Event Drop"],
            faction: "Eagle Union",
            equippable: ["BBV", "CV", "CVL"],
            stats: ["AVI +45"],
            cannons: ["4x12_7_mg_t3", "2x20_cannon_t3"],
            weapons: ["rocket_hvar"],
            weaponCount: [6],
            rld: ["10.65s"],
            linkTab: 0,
            desc: ["Không có khả năng đánh chặn"],
            code: "0/0c/17440",
            box: "yellow"
        },
        "f2a-thach": {
            name: "Brewster F2A Buffalo (Thach Squadron)",
            tier: "N/A",
            source: ["Core Data Shop"],
            faction: "Eagle Union",
            equippable: ["BBV", "CV", "CVL"],
            stats: ["AVI +45"],
            cannons: ["4x12_7_mg_t0"],
            rld: ["9.44s", "9.44s"],
            linkTab: 0,
            desc: ["Tàu mang trang bị này được tăng 4% hiệu suất trên các ô được trang bị Fighter. Hiệu ứng không cộng dồn."],
            code: "0/08/17060",
            box: "yellow"
        },
        "f6f-hellcat": {
            name: "Grumman F6F Hellcat",
            tier: "N/A",
            source: ["5-2, 13-3 Drop", "T4/T5 Eagle Tech Box", "Gear Lab"],
            faction: "Eagle Union",
            equippable: ["BBV", "CV", "CVL"],
            stats: ["AVI +45"],
            cannons: ["4x12_7_mg_t3", "2x20_cannon_t3"],
            weapons: ["bomb_500lb_t3"],
            weaponCount: [2],
            rld: ["10.90s", "9.92s"],
            linkTab: 3,
            desc: [""],
            code: "0/0d/17300",
            box: "yellow"
        },
        "f7f-tigercat": {
            name: "Grumman F7F Tigercat",
            tier: "N/A",
            source: ["Gear Lab"],
            faction: "Eagle Union",
            equippable: ["BBV", "CV", "CVL"],
            stats: ["AVI +45"],
            cannons: ["4x20_cannon_t0"],
            weapons: ["bomb_1000lb_t0"],
            weaponCount: [2],
            rld: ["10.81s", "10.81s"],
            linkTab: 0,
            desc: [""],
            code: "4/47/17360",
            box: "yellow"
        },
        "f8f-bearcat": {
            name: "Grumman F8F Bearcat",
            tier: "N/A",
            source: ["Gear Lab"],
            faction: "Eagle Union",
            equippable: ["BBV", "CV", "CVL"],
            stats: ["AVI +45"],
            cannons: ["4x20_cannon_t0"],
            weapons: ["bomb_1000lb_suisei"],
            weaponCount: [1],
            rld: ["9.64s", "9.64s"],
            linkTab: 0,
            desc: [""],
            code: "e/e7/17380",
            box: "yellow"
        },
        "f4u-vf-17": {
            name: "Vought F4U Corsair (VF-17 Squadron)",
            tier: "N/A",
            source: ["Core Data Shop"],
            faction: "Eagle Union",
            equippable: ["BBV", "CV", "CVL"],
            stats: ["AVI +45"],
            cannons: ["6x12_7_mg_t0"],
            weapons: ["bomb_500lb_t0"],
            weaponCount: [2],
            rld: ["10.20s", "10.20s"],
            linkTab: 0,
            desc: [""],
            code: "f/f7/17260",
            box: "yellow"
        },
        "xf5u-p": {
            name: "Vought XF5U Flying Flapjack (Prototype)",
            tier: "N/A",
            source: ["Gear Lab"],
            faction: "Eagle Union",
            equippable: ["BBV", "CV", "CVL"],
            stats: ["AVI +45"],
            cannons: ["4x20_cannon_t0"],
            weapons: ["bomb_1000lb_t0"],
            weaponCount: [2],
            rld: ["11.00s", "9.01s"],
            linkTab: 0,
            desc: [""],
            code: "c/c4/17420",
            box: "yellow"
        },
        "sea-hornet": {
            name: "de Havilland Sea Hornet",
            tier: "N/A",
            source: ["War Archives Drop", "Gear Lab"],
            faction: "Royal Navy",
            equippable: ["BBV", "CV", "CVL"],
            stats: ["AVI +45"],
            cannons: ["4x20_cannon_t0"],
            weapons: ["bomb_1000lb_t0"],
            weaponCount: [2],
            rld: ["10.61s", "10.61s"],
            linkTab: 0,
            desc: [""],
            code: "1/1f/27320",
            box: "yellow"
        },
        "sea-furry": {
            name: "Hawker Sea Fury",
            tier: "N/A",
            source: ["Core Data Shop", "Gear Lab"],
            faction: "Royal Navy",
            equippable: ["BBV", "CV", "CVL"],
            stats: ["AVI +45"],
            cannons: ["4x20_cannon_t0"],
            weapons: ["bomb_500lb_t3"],
            weaponCount: [2],
            rld: ["10.61s", "10.61s"],
            linkTab: 0,
            desc: [""],
            code: "d/da/27300",
            box: "yellow"
        },
        "seafang": {
            name: "Supermarine Seafang",
            tier: "N/A",
            source: ["T4/T5 Royal Tech Box", "Gear Lab"],
            faction: "Royal Navy",
            equippable: ["BBV", "CV", "CVL"],
            stats: ["AVI +45"],
            cannons: ["4x20_cannon_t3"],
            weapons: ["bomb_500lb_t3"],
            weaponCount: [2],
            rld: ["10.60s", "10.14s"],
            linkTab: 3,
            desc: [""],
            code: "5/5b/27100",
            box: "yellow"
        },
        "seafire-mk47": {
            name: "Supermarine Seafire FR Mk 47",
            tier: "N/A",
            source: ["Gear Lab"],
            faction: "Royal Navy",
            equippable: ["BBV", "CV", "CVL"],
            stats: ["AVI +45"],
            cannons: ["4x7_7_mg_t0", "2x20_cannon_t0"],
            weapons: ["bomb_500lb_t3"],
            weaponCount: [1],
            rld: ["10.61s", "10.14s"],
            linkTab: 0,
            desc: [""],
            code: "c/c4/27060",
            box: "yellow"
        },
        "n1k3a-sk2": {
            name: "Kawanishi N1K3-A Shiden Kai 2",
            tier: "N/A",
            source: ["Gear Lab"],
            faction: "Heavy Sakura",
            equippable: ["BBV", "CV", "CVL"],
            stats: ["AVI +45"],
            cannons: ["4x20_type99_cannon_t3", "2x13_mg_t1"],
            weapons: ["bomb_500lb_t3"],
            weaponCount: [2],
            rld: ["10.71s", "10.64s"],
            linkTab: 0,
            desc: [""],
            code: "5/52/37400",
            box: "yellow"
        },
        "bf-109g": {
            name: "Messerschmitt Bf 109G (Carrier-based Prototype)",
            tier: "S++",
            source: ["PR4 Research", "Gear Lab"],
            faction: "Ironblood",
            equippable: ["BBV", "CV", "CVL"],
            stats: ["AVI +45"],
            cannons: ["1x20_mg151_t3", "2x7_92_mg17_t3"],
            weapons: ["rocket_ap"],
            weaponCount: [4],
            rld: ["10.58s"],
            linkTab: 0,
            desc: ["Không có khả năng đánh chặn"],
            code: "e/ee/47160",
            box: "yellow"
        },
        "fw-190-a6r6": {
            name: "Focke-Wulf Fw 190 A-6/R6 (Carrier-based Prototype)",
            tier: "S-",
            source: ["Gear Lab"],
            faction: "Ironblood",
            equippable: ["BBV", "CV", "CVL"],
            stats: ["AVI +45"],
            cannons: ["2x20_mg_ff_t3", "2x7_92_mg17_t3", "2x20_mg151_t3"],
            weapons: ["rocket_wfr_gr21"],
            weaponCount: [2],
            rld: ["11.10s"],
            linkTab: 0,
            desc: ["Không có khả năng đánh chặn"],
            code: "c/c1/47180",
            box: "yellow"
        },
    }
};