equipData["Surface Torpedo"] = {
    subCategories: [
        { id: "trp-light", name: "Giáp Light Đơn" }
    ],
    tierlists: {
    },
    filterConfig: {
        property: "torpType",
        fallbackItemValue: "trp",
        buttons: [
            { value: "all", label: "Danh Sách Tổng" },
            { value: "trp", label: "Chỉ Torpedo" },
            { value: "gm", label: "Chỉ Missile" }
        ]
    }
};

equipDetails["Surface Torpedo"] = {
    "raibow_sur_torp": {
        "quint-610": {
            name: "610mm Quintuple Torpedo Mount",
            torpType: "trp",
            tier: "N/A",
            source: ["Gear Lab"],
            faction: "Heavy Sakura",
            equippable: ["DD", "CL", "CA", "CB", "BC"],
            stats: ["TRP +70"],
            ammoType: "Torp",
            ammoMod: "80% / 100% / 130%",
            rld: ["28.60s"],
            dmg: ["5", "190"],
            range: "80-120",
            coef: 1.18,
            linkTab: 0,
            desc: [],
            code: "0/05/35300",
            box: "rainbow"
        },
        "quint-533-hom": {
            name: "533mm Quintuple Homing Torpedo Mount",
            torpType: "trp",
            tier: "N/A",
            source: ["Gear Lab"],
            faction: "Ironblood",
            equippable: ["DD", "CL", "CA", "CB", "BC"],
            stats: ["TRP +70"],
            ammoType: "Torp",
            ammoMod: "80% / 100% / 130%",
            rld: ["29.40s"],
            dmg: ["5", "145"],
            range: "70-110",
            coef: 1.18,
            linkTab: 0,
            desc: ["Ngư lôi từ trường."],
            code: "7/7b/45200",
            box: "rainbow"
        },
    },
    "yellow_sur_torp": {
        "quint-533": {
            name: "533mm Quintuple Torpedo Mount",
            torpType: "trp",
            tier: "N/A",
            source: ["7-4, War Archives Drop", "Non-Ironblood T4/T5 Tech Box"],
            faction: "Universal",
            equippable: ["DD", "CL", "CA", "CB", "BC"],
            stats: ["TRP +45"],
            ammoType: "Torp",
            ammoMod: "80% / 100% / 130%",
            rld: ["26.44s"],
            dmg: ["5", "156"],
            range: "70-110",
            coef: 1.18,
            linkTab: 3,
            desc: [""],
            code: "b/b3/5200",
            box: "yellow"
        },
        "quad-533-mk35-qcl": {
            name: "533mm Mark 35 Torpedo Mount (Quad Consecutive Launch)",
            torpType: "trp",
            tier: "N/A",
            source: ["Gear Lab"],
            faction: "Eagle Union",
            equippable: ["DD", "CL", "CA", "CB", "BC"],
            stats: ["TRP +45"],
            ammoType: "Torp",
            ammoMod: "80% / 100% / 130%",
            rld: ["26.00s"],
            dmg: ["4", "152"],
            range: "70-110",
            coef: 1.18,
            linkTab: 0,
            desc: ["Ngư lôi từ trường phóng lần lượt từng quả.", "Có thể đánh trúng tàu ngầm (35% sát thương)."],
            code: "5/5e/15300",
            box: "yellow"
        },
        "quint-533-mk17": {
            name: "533mm Quintuple Torpedo Mount Mk 17",
            torpType: "trp",
            tier: "N/A",
            source: ["Gear Lab"],
            faction: "Eagle Union",
            equippable: ["DD", "CL", "CA", "CB", "BC"],
            stats: ["TRP +45"],
            ammoType: "Torp",
            ammoMod: "80% / 100% / 130%",
            rld: ["26.40s"],
            dmg: ["5", "160"],
            range: "70-110",
            coef: 1.18,
            linkTab: 0,
            desc: [""],
            code: "b/bf/15240",
            box: "yellow"
        },
        "quint-533-mkix": {
            name: "533mm Quintuple Torpedo Mount Mk IX",
            torpType: "trp",
            tier: "N/A",
            source: ["Gear Lab"],
            faction: "Royal Navy",
            equippable: ["DD", "CL", "CA", "CB", "BC"],
            stats: ["TRP +45"],
            ammoType: "Torp",
            ammoMod: "80% / 100% / 130%",
            rld: ["28.00s"],
            dmg: ["5", "172"],
            range: "70-110",
            coef: 1.18,
            linkTab: 0,
            desc: ["Ngư lôi phóng lần lượt từng quả."],
            code: "d/d3/25040",
            box: "yellow"
        },
        "quad-610": {
            name: "610mm Quadruple Torpedo Mount",
            torpType: "trp",
            tier: "N/A",
            source: ["6-4, 8-2, 10-4, 11-2, 12-2 Drop", "T4/T5 Sakura Tech Box", "Gear Lab"],
            faction: "Heavy Sakura",
            equippable: ["DD", "CL", "CA", "CB", "BC"],
            stats: ["TRP +45"],
            ammoType: "Torp",
            ammoMod: "80% / 100% / 130%",
            rld: ["28.54s"],
            dmg: ["4", "206"],
            range: "80-120",
            coef: 1.18,
            linkTab: 3,
            desc: [""],
            code: "1/14/35200",
            box: "yellow"
        },
        "quad-610-kai": {
            name: "610mm Quadruple Torpedo Mount Kai",
            torpType: "trp",
            tier: "N/A",
            source: ["Gear Lab"],
            faction: "Heavy Sakura",
            equippable: ["DD", "CL", "CA", "CB", "BC"],
            stats: ["TRP +45"],
            ammoType: "Torp",
            ammoMod: "80% / 100% / 130%",
            rld: ["28.33s"],
            dmg: ["4", "210"],
            range: "80-120",
            coef: 1.18,
            linkTab: 0,
            desc: [""],
            code: "e/ea/35260",
            box: "yellow"
        },
        "quad-610-cruiser": {
            name: "610mm Quadruple Torpedo Mount (Cruiser)",
            torpType: "trp",
            tier: "N/A",
            source: ["Gear Lab"],
            faction: "Heavy Sakura",
            equippable: ["DD", "CL", "CA", "CB", "BC"],
            stats: ["TRP +45"],
            ammoType: "Torp",
            ammoMod: "80% / 100% / 130%",
            rld: ["27.00s"],
            dmg: ["4", "235"],
            range: "90-110",
            coef: 1.18,
            linkTab: 0,
            desc: [""],
            code: "b/b4/35280",
            box: "yellow"
        },
        "quad-533-hom": {
            name: "533mm Quadruple Homing Torpedo Mount",
            torpType: "trp",
            tier: "N/A",
            source: ["War Archives Drop", "T4/T5 Iron Blood Tech Box", "Gear Lab"],
            faction: "Ironblood",
            equippable: ["DD", "CL", "CA", "CB", "BC"],
            stats: ["TRP +45"],
            ammoType: "Torp",
            ammoMod: "80% / 100% / 130%",
            rld: ["25.47s"],
            dmg: ["4", "145"],
            range: "70-110",
            coef: 1.18,
            linkTab: 3,
            desc: ["Ngư lôi từ trường."],
            code: "5/51/45100",
            box: "yellow"
        },
        "quint-533-hom": {
            name: "533mm Quintuple Homing Torpedo Mount",
            torpType: "trp",
            tier: "N/A",
            source: ["T4/T5 Iron Blood Tech Box"],
            faction: "Ironblood",
            equippable: ["DD", "CL", "CA", "CB", "BC"],
            stats: ["TRP +45"],
            ammoType: "Torp",
            ammoMod: "80% / 100% / 130%",
            rld: ["30.93s"],
            dmg: ["4", "133"],
            range: "70-110",
            coef: 1.18,
            linkTab: 2,
            desc: ["Ngư lôi từ trường."],
            code: "7/7b/45200",
            box: "yellow"
        },
        "quad-533-mag": {
            name: "533mm Improved Quadruple Magnetic Torpedo Mount",
            torpType: "trp",
            tier: "N/A",
            source: ["Welcome to Little Academy Mileston Event Shop", "Substellar Crepuscule Event Shop"],
            faction: "Ironblood",
            equippable: ["DD", "CL", "CA", "CB", "BC"],
            stats: ["TRP +45"],
            ammoType: "Torp",
            ammoMod: "80% / 100% / 130%",
            rld: ["25.70s"],
            dmg: ["4", "157"],
            range: "70-110",
            coef: 1.18,
            linkTab: 0,
            desc: ["Ngư lôi từ trường."],
            code: "6/64/45160",
            box: "yellow"
        },
        "sy_1a": {
            name: "SY-1A Missile",
            torpType: "gm",
            tier: "N/A",
            source: ["Spring Festive Fiasco Event Reward"],
            faction: "Dragon Empery",
            stats: ["TRP +45"],
            ammoType: "Missile",
            ammoMod: "130% / 110% / 80%",
            rld: ["25.60s"],
            dmg: ["4", "317"],
            range: "115-125",
            coef: 1.18,
            linkTab: 0,
            desc: ["Tên lửa dẫn đường.", "Có 50% khả năng gây cháy (phân loại cháy DD)."],
            code: "0/05/56020",
            box: "yellow"
        },
        "sy_1": {
            name: "SY-1 Missile",
            torpType: "gm",
            tier: "N/A",
            source: ["Core Data Shop"],
            faction: "Dragon Empery",
            stats: ["TRP +45"],
            ammoType: "Missile",
            ammoMod: "130% / 110% / 80%",
            rld: ["26.27s"],
            dmg: ["4", "264"],
            range: "120",
            coef: 1.18,
            linkTab: 0,
            desc: ["Tên lửa dẫn đường.", "Có 50% khả năng gây cháy (phân loại cháy DD)."],
            code: "7/77/56000",
            box: "yellow"
        },
        "quad-533-si270": {
            name: "Prototype 533mm Quadruple Si270 Torpedo Mount",
            torpType: "trp",
            tier: "N/A",
            source: ["PR8 Research"],
            faction: "Sardegna Empire",
            equippable: ["DD", "CL", "CA", "CB", "BC"],
            stats: ["TRP +45"],
            ammoType: "Torp",
            ammoMod: "80% / 100% / 130%",
            rld: ["21.00s"],
            dmg: ["4", "135"],
            range: "140-160",
            coef: 1.18,
            linkTab: 0,
            desc: ["Ngư lôi phóng chia thành hai lượt."],
            code: "d/d3/56280",
            box: "yellow"
        },
        "quad-550-i-am": {
            name: "550mm Quadruple Torpedo Mount Improved (Ammo Mod)",
            torpType: "trp",
            tier: "N/A",
            source: ["Gear Lab"],
            faction: "Iris Libre",
            equippable: ["DD", "CL", "CA", "CB", "BC"],
            stats: ["TRP +45"],
            ammoType: "Torp",
            ammoMod: "130% / 100% / 80%",
            rld: ["24.30s"],
            dmg: ["4", "182"],
            range: "80-100",
            coef: 1.18,
            linkTab: 0,
            desc: [""],
            code: "0/09/5640",
            box: "yellow"
        },
        "twin-triple-550": {
            name: "550mm Torpedo Mount (Twin + Triple)",
            torpType: "trp",
            tier: "N/A",
            source: ["Light of the Martyrium Event Shop"],
            faction: "Iris Libre",
            equippable: ["DD", "CL", "CA", "CB", "BC"],
            stats: ["TRP +45"],
            ammoType: "Torp",
            ammoMod: "80% / 100% / 130%",
            rld: ["29.00s"],
            dmg: ["5", "182"],
            range: "80-100",
            coef: 1.18,
            linkTab: 0,
            desc: ["Ngư lôi phóng chia thành hai lượt."],
            code: "2/20/5660",
            box: "yellow"
        },
        "triple-550-i-am": {
            name: "550mm Triple Torpedo Mount Improved (Ammo Mod)",
            torpType: "trp",
            tier: "N/A",
            source: ["PR9 Research"],
            faction: "Iris Libre",
            equippable: ["DD", "CL", "CA", "CB", "BC"],
            stats: ["TRP +45"],
            ammoType: "Torp",
            ammoMod: "130% / 100% / 80%",
            rld: ["21.00s"],
            dmg: ["3", "182"],
            range: "80-100",
            coef: 1.18,
            linkTab: 0,
            desc: ["Ngư lôi từ trường"],
            code: "b/b5/5680",
            box: "yellow"
        },
    },
    "purple_sur_torp": {
        "triple-533-hom": {
            name: "533mm Triple Homing Torpedo Mount",
            torpType: "trp",
            tier: "N/A",
            source: ["T3/T4 Iron Blood Tech Box", "Gear Lab"],
            faction: "Ironblood",
            equippable: ["DD", "CL", "CA", "CB", "BC"],
            stats: ["TRP +25"],
            ammoType: "Torp",
            ammoMod: "80% / 100% / 130%",
            rld: ["22.21s"],
            dmg: ["3", "145"],
            range: "70-110",
            coef: 1.04,
            linkTab: 3,
            desc: ["Ngư lôi từ trường."],
            code: "1/1e/45000",
            box: "purple"
        },
    },
}