shipDetails["BB"] = {
    "rainbow_bb": {
        "new_jersey": {
            name: "New Jersey",
            source: ["Heavy + Special Build", "UR Exchange"],
            faction: "Eagle Union",
            rarity: "Ultra Rare",
            code: "d/d5",
            box: "rainbow",
            equipSlot: [["BBGM"], ["DDGM"], ["AAGM", "AATFGM"]],
            slotAmount: [3, 3, 1],
            slotEff: ["155", "210", "130"]
        },
        "lion": {
            name: "Lion",
            source: ["A Rose on the High Tower Event Build"],
            faction: "Royal Navy",
            rarity: "Ultra Rare",
            code: "1/1a",
            box: "rainbow",
            equipSlot: [["BBGM"], ["CLGM", "DDGM"], ["AAGM", "AATFGM"]],
            slotAmount: [3, 3, 1],
            slotEff: ["170", "200", "120"]
        },
        "vanguard": {
            name: "Vanguard",
            source: ["Heavy + Special Build", "UR Exchange"],
            faction: "Royal Navy",
            rarity: "Ultra Rare",
            code: "c/c2",
            box: "rainbow",
            equipSlot: [["BBGM"], ["CLGM", "DDGM"], ["AAGM", "AATFGM"]],
            slotAmount: [3, 3, 1],
            slotEff: ["145", "180", "130"],
            customRules: [
                {
                    type: "FACTION_SLOT_EFF_BONUS",
                    targetSlotIndex: 2,          
                    requiredFaction: "Royal Navy",
                    minCount: 1,           
                    bonus: 30             
                }
            ]
        },
        "warspite_kai": {
            name: "Warspite Kai",
            source: ["Warspite + Prototype Shop"],
            faction: "Royal Navy",
            rarity: "Ultra Rare",
            code: "yanzhan_g",
            box: "rainbow",
            equipSlot: [["BBGM"], ["CLGM", "DDGM"], ["AAGM", "AATFGM"]],
            slotAmount: [3, 3, 1],
            slotEff: ["140", "200", "115"],
            customRules: [
                {
                    type: "EQUIP_ID_SLOT_EFF_BONUS",
                    targetSlotIndex: 0,
                    requiredEquipId: "oldladys_royalsword",
                    bonus: 10
                }
            ]
        },
        "musashi": {
            name: "Musashi",
            source: ["Heavy + Special Build", "UR Exchange"],
            faction: "Heavy Sakura",
            rarity: "Ultra Rare",
            code: "c/c9",
            box: "rainbow",
            equipSlot: [["BBGM"], ["CLGM", "DDGM"], ["AAGM", "AATFGM"]],
            slotAmount: [3, 3, 1],
            slotEff: ["155", "220", "100"],
        },
        "bismarck_zwei": {
            name: "Bismarck Zwei",
            source: ["Heavy + Special Build", "UR Exchange"],
            faction: "Ironblood",
            rarity: "Ultra Rare",
            code: "6/63",
            box: "rainbow",
            equipSlot: [["BBGM"], ["CLGM", "DDGM"], ["AAGM", "AATFGM"]],
            slotAmount: [3, 3, 1],
            slotEff: ["155", "200", "110"],
        },
        "friedrich_der_große": {
            name: "Friedrich der Große",
            source: ["PR2 Research"],
            faction: "Ironblood",
            rarity: "Decisive",
            code: "7/7f",
            box: "rainbow",
            equipSlot: [["BBGM"], ["CLGM", "DDGM"], ["AAGM", "AATFGM"]],
            slotAmount: [3, 3, 1],
            slotEff: ["160", "220", "100"],
        },
        "götz_von_berlichingen": {
            name: "Götz von Berlichingen",
            source: ["Alliance Before the Hagiobull Event Build"],
            faction: "Ironblood",
            rarity: "Ultra Rare",
            code: "f/f0",
            box: "rainbow",
            equipSlot: [["BBGM"], ["CLGM", "DDGM"], ["AAGM", "AATFGM"]],
            slotAmount: [3, 3, 1],
            slotEff: ["160", "210", "90"],
        },
        "mecklenburg": {
            name: "Mecklenburg",
            source: ["PR8 Research"],
            faction: "Ironblood",
            rarity: "Decisive",
            code: "7/74",
            box: "rainbow",
            equipSlot: [["BBGM"], ["CLGM", "DDGM"], ["AAGM", "AATFGM"]],
            slotAmount: [3, 3, 1],
            slotEff: ["170", "220", "120"],
        },
        "ulrich_von_hutten": {
            name: "Ulrich von Hutten",
            source: ["Heavy + Special Build", "UR Exchange"],
            faction: "Ironblood",
            rarity: "Ultra Rare",
            code: "d/d4",
            box: "rainbow",
            equipSlot: [["BBGM"], ["CLGM", "DDGM"], ["AAGM", "AATFGM"]],
            slotAmount: [3, 3, 1],
            slotEff: ["155", "210", "90"],
        },
        "raffaello": {
            name: "Raffaello",
            source: ["Paradiso of Shackled Light Event Build"],
            faction: "Sardegna Empire",
            rarity: "Ultra Rare",
            code: "4/45",
            box: "rainbow",
            equipSlot: [["BBGM"], ["CLGM", "DDGM"], ["AAGM", "AATFGM"]],
            slotAmount: [3, 3, 1],
            slotEff: ["150", "200", "100"],
        },
        "sovetsky_soyuz": {
            name: "Sovetsky Soyuz",
            source: ["Snowrealm Peregrination Event Build"],
            faction: "Northern Parliament",
            rarity: "Ultra Rare",
            code: "4/44",
            box: "rainbow",
            equipSlot: [["BBGM"], ["CLGM", "DDGM"], ["AAGM", "AATFGM"]],
            slotAmount: [3, 3, 1],
            slotEff: ["150", "200", "120"],
        },
        "alsace": {
            name: "Alsace",
            source: ["Light of the Martyrium Event Build"],
            faction: "Iris Libre",
            rarity: "Ultra Rare",
            code: "0/0e",
            box: "rainbow",
            equipSlot: [["BBGM"], ["CLGM", "DDGM"], ["AAGM", "AATFGM"]],
            slotAmount: [3, 3, 1],
            slotEff: ["145", "200", "100"],
        },
    },
};